export const config: {
    LOCATION: string,
    CYCLE_TIME: number,
    HARVEST_RATIO: number,
    QUEUE_ID: number,
    DAEMON_FILE: string,
    MANAGER_FILE: string,
    FARM_FILE: string,
    NODE_FILE: string,
    COMPONENT_FILE: string,
    CONFIG_FILE: string,
    DISPLAY_TAIL: boolean,
} = {
    LOCATION: 'foodnstuff',
    CYCLE_TIME: 10 * 1000, //ms
    HARVEST_RATIO: 50 / 100,
    QUEUE_ID: 1,
    DAEMON_FILE: '/hacknet/hacknet-daemon.js',
    MANAGER_FILE: '/hacknet/manager.js',
    FARM_FILE: '/hacknet/farm.js',
    NODE_FILE: '/hacknet/node.js',
    COMPONENT_FILE: '/hacknet/component.js',
    CONFIG_FILE: '/hacknet/config.js',
    DISPLAY_TAIL: false,
};