@startuml
skinparam componentStyle rectangle

rectangle {
    hexagon Jarvis #Business

    component JarvisApp #Application
    interface JarvisPort #Application

    interface HydraJarvisPort
    component HydraAdapter #Implementation

    interface SherlockJarvisPort
    component SherlockAdapter #Implementation

    interface HacknetJarvisPort
    component HacknetAdapter #Implementation

    interface NsJarvisPort
    component JarvisNsAdapter #Implementation
}

rectangle {
    component HydraApp #Application
    interface HydraAPI #Application

    hexagon Hydra #Business
    interface HydraPort

    interface HydraNsPort
    component HydraNsAdapter #Implementation

    component HydraFactory #Implementation
}

rectangle {
    component SherlockApp #Application
    interface SherlockAPI #Application

    hexagon Sherlock #Business
    interface SherlockPort

    interface SherlockNsPort
    component SherlockNsAdapter #Implementation

    component SherlockFactory #Implementation
}

rectangle {
    component HacknetApp #Application
    interface HacknetAPI #Application

    hexagon Hacknet #Business
    interface HacknetPort

    interface HacknetNsPort
    component HacknetNsAdapter #Implementation

    component HacknetFactory #Implementation
}

component LogNsAdapter #Implementation

rectangle {
    interface NsInterface #Technology
    component NS #Technology
}

'Jarvis
    ' Application
    JarvisApp -r-> JarvisPort

    'Adapters
    JarvisPort -r-> Jarvis
    Jarvis --> HydraJarvisPort
    HydraJarvisPort --> HydraAdapter
    Jarvis --> HacknetJarvisPort
    HacknetJarvisPort --> HacknetAdapter
    Jarvis --> SherlockJarvisPort
    SherlockJarvisPort --> SherlockAdapter
    Jarvis --> NsJarvisPort
    NsJarvisPort --> JarvisNsAdapter

' Hydra
    HydraAPI -l-> HydraApp
    HydraApp --> HydraFactory
    HydraApp --> HydraPort
    HydraPort --> Hydra
    Hydra -r-> HydraNsPort
    HydraNsPort --> HydraNsAdapter
    Hydra ---> LogNsAdapter
    HydraFactory ..|> HydraNsAdapter
    HydraFactory ..|> Hydra

' Sherlock
    SherlockAPI -l-> SherlockApp
    SherlockApp --> SherlockFactory
    SherlockApp --> SherlockPort
    SherlockPort --> Sherlock
    Sherlock -r-> SherlockNsPort
    SherlockNsPort --> SherlockNsAdapter
    Sherlock ---> LogNsAdapter
    SherlockFactory ..|> SherlockNsAdapter
    SherlockFactory ..|> Sherlock

' Hacknet
    HacknetAPI -r-> HacknetApp
    HacknetApp --> HacknetFactory
    HacknetApp --> HacknetPort
    HacknetPort --> Hacknet
    Hacknet -r-> HacknetNsPort
    HacknetNsPort --> HacknetNsAdapter
    Hacknet ---> LogNsAdapter
    HacknetFactory ..|> HacknetNsAdapter
    HacknetFactory ..|> Hacknet

' NS
    LogNsAdapter --> NsInterface
    NsInterface --> NS

' Integration
    ' Jarvis to modules
    HacknetAdapter --> HacknetAPI
    SherlockAdapter --> SherlockAPI
    HydraAdapter --> HydraAPI

    ' Modules to NS
    SherlockNsAdapter --> NsInterface
    HydraNsAdapter --> NsInterface
    HacknetNsAdapter --> NsInterface
    JarvisNsAdapter --> NsInterface

@enduml