@startuml
skinparam componentStyle rectangle
skinparam linetype polyline

rectangle {
    hexagon Jarvis #Business

    component JarvisApp #Application
    interface JarvisPort #Application

    component HydraAdapter #Implementation
    component SherlockAdapter #Implementation
    component HacknetAdapter #Implementation
    component JarvisNsAdapter #Implementation
}

rectangle {
    component HydraApp #Application
    interface HydraAPI #Application

    hexagon Hydra #Business
    interface HydraPort

    component HydraNsAdapter #Implementation

    component HydraFactory #Implementation
}

rectangle {
    component SherlockDaemon #Application
    interface SherlockAPI #Application

    hexagon Sherlock #Business
    interface SherlockPort

    component SherlockNsAdapter #Implementation
}

rectangle {
    component HacknetDaemon #Application
    interface HacknetAPI #Application

    hexagon Hacknet #Business
    interface HacknetPort

    component HacknetNsAdapter #Implementation
}

component LogNsAdapter #Implementation

rectangle {
    interface JarvisNsPort #Technology
    interface HacknetNsPort #Technology
    interface SherlockNsPort #Technology
    interface HydraNsPort #Technology
    interface LogNsPort #Technology

    component NS #Technology
}

'Jarvis
    ' Application
    JarvisApp -r-> JarvisPort

    'Adapters
    JarvisPort -r-> Jarvis
    Jarvis --> HydraAdapter
    Jarvis --> HacknetAdapter
    Jarvis --> SherlockAdapter
    Jarvis --> JarvisNsAdapter

' Hydra
    HydraAPI -l-> HydraApp
    HydraApp --> HydraFactory
    HydraApp --> HydraPort
    HydraPort --> Hydra
    Hydra --> HydraNsAdapter
    Hydra ---> LogNsAdapter
    HydraFactory ..|> HydraNsAdapter
    HydraFactory ..|> Hydra

' Sherlock
    SherlockAPI -l-> SherlockDaemon
    SherlockDaemon --> SherlockPort
    SherlockPort --> Sherlock
    Sherlock --> SherlockNsAdapter
    Sherlock ---> LogNsAdapter
    SherlockDaemon ..|> SherlockNsAdapter
    SherlockDaemon ..|> LogNsAdapter
    SherlockDaemon ..|> Sherlock

' Hacknet
    HacknetAPI -r-> HacknetDaemon
    HacknetDaemon --> HacknetPort
    HacknetPort --> Hacknet
    Hacknet --> HacknetNsAdapter
    Hacknet ---> LogNsAdapter
    HacknetDaemon ..|> HacknetNsAdapter
    HacknetDaemon ..|> LogNsAdapter
    HacknetDaemon ..|> Hacknet

' NS
    LogNsAdapter --> LogNsPort
    JarvisNsPort --> NS
    SherlockNsPort --> NS
    HacknetNsPort --> NS
    HydraNsPort --> NS
    LogNsPort --> NS

' Integration
    ' Jarvis to modules
    HacknetAdapter --> HacknetAPI
    SherlockAdapter --> SherlockAPI
    HydraAdapter --> HydraAPI

    ' Modules to NS
    SherlockNsAdapter --> SherlockNsPort
    HydraNsAdapter --> HydraNsPort
    HacknetNsAdapter --> HacknetNsPort
    JarvisNsAdapter --> JarvisNsPort

@enduml