@startuml
'https://plantuml-editor.kkeisuke.dev/

'interface NetworkLastUpdate <<Q, skyblue>> #aliceblue;line:deepskyblue {}

package 1-Hacknet-BN9 #technology{
  hide empty member

  interface nextUpgrade <<Q, skyblue>> #aliceblue;line:deepskyblue {
    +timestampOfNextUpgrade : int
  }
  'entity hacknet <<F, lawngreen>> #technology;line:green {}

  class HacknetDaemon {
    +deploy() : Promise
    +activate()
    +operate()
  }

  class HacknetFarm {
    +MAX_NODE_COUNT
    +nodeCount
    +newNodeCost
    +nodeList : HacknetNode[]
    +productionRate
    +totalProduction

    +buyNewNode()
  }

  class HacknetNode {
    #Component : {int, int, int, int}
    +id
    +level
    +ram
    +cores
    +levelUpgradeCost
    +ramUpgradeCost
    +coreUpgradeCost
    +productionRate
    +totalProduction

    +getUpgradeCost(Component)
    +upgrade(Component, quantity)
  }
}

package 2-Sherlock #technology{

  class WatsonDaemon {
    +call()
    +wakeup()
  }

  class Contract {
    +name
    +location
    +type
    +data
    +solution
    +reward
  }

  class Sherlock {
    +solve() : Contract
  }
}

package 3-Network #technology{

  class Network {
    +nodesList : Server[]
    +nodesNameList
    +nodesCount
    +isFullyOwned

    +getNodes() : Server[]
    +getNode() : Server
  }

  class Node {
    +hostname
    +hasAdminRights
    +requiredHackingSkill
    +numOpenPortsRequired
    +securityMin
    +moneyMax
    +ramMax
    +purchasedByPlayer
    +growthFactor
    +isPotentialTarget
  }
}

package 4-Jarvis #cornsilk{
  hide empty member
  'entity jarvisKibana <<F, lawngreen>> #technology;line:green{}

  class JarvisDaemon {
    +hacknetDaemon : HacknetDaemon

    +network : Network
    -cycleTime : int
    
    +warmingUp()
    +wakeup()
    -hacknetInspection()
    -wakeupWatson()
    -zombifyAvailableServers()
  }

  class SkeletonKey {
    +keyCount : int
    -KEYS : str[]

    +nuke(target) : bool
    -openPorts(str) : int
    -requestRootAccess(str) : bool
  }

  class CONFIG{}
}

package 6-Hydra #pink{

  class IcaDaemon {}

  class Agent47 {}

  class HydraDaemon {}

  class ShivaDaemon {}

  class Hack <Malware> {
    +duration
    +unitMoneyDecrease
    +unitSecurityIncrease
    +successRate

    +threadsQtyToDecreaseMoneyOf()
  }

  class Weaken <Malware> {
    +duration
    +unitMoneyImpact
    +unitSecurityDecrease

    +threadsQtyToDecreaseSecurityOf()
  }

  class Grow <Malware> {
    +duration
    +unitMoneyIncrease
    +unitSecurityIncrease

    +threadsQtyToIncreaseMoneyOf()
  }

  abstract Malware {
    +filePath
    +targetName
    +runnerName
    +marketImpact
    +coresQty
    +ramRequirement

    +deploy()
    +execute()
  }

}

'package 7-WolfStreet-BN8 #pink{
  
  'entity wolfStreetKibana  <<F, lawngreen>> #technology;line:green {}
 ' entity businessRelationship <<F, lawngreen>> #technology;line:green {}
  
  'class TradingFloor {}
  'class Trader {}
  'class Market {}
  'class Stock {}
'}

'package Underworld-BN2 {}
'package Corporatocracy-BN3 {}

'package Singularity-BN4 #pink{
  '=> singularity functions
  'class CareerCoach {}
  'class Job {}
'}

'package AI-BN5 {} => getBitNodeMultipliers() + formulas
'package Bladeburners-BN6/7 {}
'Package HacknetServers-BM9 {}
'Package Sleeves-BN10{}


'JARVIS'
JarvisDaemon -u- CONFIG
JarvisDaemon -u- SkeletonKey

JarvisDaemon      -l-     HacknetDaemon : > activate
nextUpgrade       -      JarvisDaemon   : < listen to
JarvisDaemon      -r-    Network         : > run
JarvisDaemon      -u-    WatsonDaemon   : > activate
JarvisDaemon      --     HydraDaemon    : > activate
JarvisDaemon      --     IcaDaemon    : > activate
'JarvisDaemon      -u--   TradingFloor
'JarvisDaemon      -u--   CareerCoach

'HACKNET'
HacknetDaemon     -- HacknetFarm
HacknetDaemon     .u.|> nextUpgrade : > publish
HacknetFarm   "1" *-d- "n" HacknetNode

'CONTRACTS'
WatsonDaemon -u- Contract
WatsonDaemon -r- Sherlock
Sherlock -l- Contract

'NETWORK'
Network "1" *-r- "n" Node

'HYDRA'
IcaDaemon -- Agent47
HydraDaemon "1" -- "n" ShivaDaemon
ShivaDaemon -d- Hack
ShivaDaemon -d- Grow
ShivaDaemon -d- Weaken
Agent47 -d- Grow
Agent47 -d- Weaken
Hack -d- Malware
Grow -d- Malware
Weaken -d- Malware

'TRADING'
'TradingFloor .l|> businessRelationship
'Trader       .d.|> businessRelationship

'TradingFloor -u- Trader
'TradingFloor -u- Market

'Trader -r- Stock
'Market -l- Stock

'JOB'
'CareerCoach -u- Job

@enduml
